export const coursesList = [
  "ND Agricultural Technology",
  "ND Animal Health and Production Technology",
  "ND Fisheries Technology",
  "ND Forestry and Environmental Technology",
  "ND Home and Rural Economics",
  "ND Horticultural Technology",
  "ND Hydrology and Water Resource Management",
  "ND Irrigation Agronomy Technology",
  "ND Oceanography and Fisheries Sciences",
  "ND Organic Agricultural Technology",
  "ND Veterinary Laboratory Technology",
  "ND Wildlife and Eco-Tourism Management",
  "ND Wood and Paper Technology",
  "HND Agribusiness Management",
  "HND Agricultural Extension and Management",
  "HND Animal Production Technology",
  "HND Animal Health Technology",
  "HND Crop Production Technology",
  "HND Fisheries Technology",
  "HND Forestry and Environmental Technology",
  "HND Home and Rural Economics",
  "HND Horticulture Technology",
  "HND Pasture and Range Management",
  "HND Pest Management Technology",
  "HND Pulp and Paper Technology",
  "HND Soil Science and Land Resources",
  "HND Veterinary Laboratory Technology",
  "HND Wildlife and Eco-Tourism Management",
  "HND Wood and Paper Technology",
  "ND Art and Industrial Design",
  "ND Fashion Design and Clothing Technology",
  "ND Graphics Design and Advertising",
  "ND Interior Design",
  "ND Library and Information Science",
  "ND Mass Communication",
  "ND Multimedia Technology",
  "ND Music Technology",
  "ND Photography",
  "ND Printing Technology",
  "HND Art and Industrial Design (Ceramic)",
  "HND Art and Industrial Design (Graphics)",
  "HND Art and Industrial Design (Painting)",
  "HND Art and Industrial Design (Sculpture)",
  "HND Art and Industrial Design (Textiles)",
  "HND Book Publishing",
  "HND Fashion Design and Clothing Technology",
  "HND Film and Multimedia Production",
  "HND Journalism and Media Production",
  "HND Library and Information Science",
  "HND Music Technology",
  "HND Printing Technology",
  "HND Strategic Communication and Media Studies",
  "ND Architectural Technology",
  "ND Building Technology",
  "ND Cartography and Geographic Information Science",
  "ND Estate Management and Valuation",
  "ND Photogrammetry and Remote Sensing",
  "ND Project Management",
  "ND Quantity Surveying",
  "ND Surveying and Geo-informatics",
  "ND Transport and Logistics Management",
  "ND Transport Planning and Management",
  "ND Transport Safety Technology",
  "ND Transport Technology",
  "ND Urban and Regional Planning",
  "HND Architectural Technology",
  "HND Cartography and Geographic Information Science",
  "HND Estate Management and Valuation",
  "HND Photogrammetry and Remote Sensing",
  "HND Quantity Surveying",
  "HND Surveying and Geo-informatics",
  "HND Transport Planning and Management",
  "HND Urban and Regional Planning",
  "ND Agricultural and Bio-Environmental Engineering Technology",
  "ND Aircraft Engineering Technology",
  "ND Auto-Body Technology",
  "ND Cement Engineering Technology",
  "ND Chemical Engineering Technology",
  "ND Civil Engineering Technology",
  "ND Computer Engineering Technology",
  "ND Electrical and Electronic Engineering Technology",
  "ND Explosive Ordinance Technology",
  "ND Foundry Technology",
  "ND Industrial Maintenance Engineering Technology",
  "ND Industrial Safety and Environmental Engineering Technology",
  "ND Marine Engineering Technology",
  "ND Mechanical Engineering Technology",
  "ND Mechatronics Engineering Technology",
  "ND Metallurgy",
  "ND Mineral and Petroleum Resources Engineering Technology",
  "ND Petroleum and Gas Processing Engineering Technology",
  "ND Pipeline Engineering Technology",
  "ND Railway Engineering Technology",
  "ND Renewable Energy Technology",
  "ND Shipping Engineering Technology",
  "ND Water Resources Engineering Technology",
  "ND Welding and Fabrication Engineering Technology",
  "HND Agricultural and Bio-Environmental Engineering(Post-Harvest)",
  "HND Agricultural and Bio-Environmental Engineering (Farm Power and Machinery)",
  "HND Agricultural and Bio-Environmental Engineering (Soil and Water)",
  "HND Aircraft Engineering Technology (Air Frame)",
  "HND Aircraft Engineering Technology (Avionics)",
  "HND Chemical Engineering Technology",
  "HND Civil Engineering Technology",
  "HND Computer Engineering Technology",
  "HND Electrical and Electronic Engineering Technology (Electronics & Telecommunications)",
  "HND Electrical and Electronic Engineering Technology (Instrumentation & Control)",
  "HND Electrical and Electronic Engineering Technology (Power & Machines)",
  "HND Explosive Ordinance Technology",
  "HND Foundry Technology",
  "HND Industrial Maintenance Engineering Technology",
  "HND Industrial Safety and Environmental Engineering Technology (Environmental)",
  "HND Industrial Safety and Environmental Engineering Technology (Industrial Safety)",
  "HND Marine Engineering Technology",
  "HND Mechanical Engineering Technology (Automotive)",
  "HND Mechanical Engineering Technology (Manufacturing)",
  "HND Mechanical Engineering Technology (Plant Engineering)",
  "HND Mechanical Engineering Technology (Power and Plant)",
  "HND Mechatronics Engineering Technology (Industrial)",
  "HND Mechatronics Engineering Technology (Automotive)",
  "HND Metallurgy",
  "HND Mineral and Petroleum Resources Engineering Technology (Geology)",
  "HND Mineral & Petroleum Resources Engineering Technology (Minerals)",
  "HND Mineral &Petroleum Resources Engineering Technology (Mining)",
  "HND Solar Photovoltaic Engineering Technology",
  "HND Solar Thermal Engineering Technology",
  "HND Water Resources Engineering Technology",
  "HND Welding and Fabrication Engineering Technology",
  "ND Accountancy",
  "ND Banking and Finance",
  "ND Business Administration & Management",
  "ND Common and Islamic Law",
  "ND Cooperative Economics & Management",
  "ND Crime Management",
  "ND Cultural Administration and Resource Management",
  "ND Freight Forwarding",
  "ND Industrial and Labour Relations",
  "ND Insurance",
  "ND Law",
  "ND Local Government Studies",
  "ND Maritime Transport and Business Studies",
  "ND Marketing",
  "ND Microfinance and Enterprise Development",
  "ND Office Technology and Management",
  "ND Pension Administration and Management",
  "ND Petroleum Marketing and Business Studies",
  "ND Procurement and Supply Chain Management",
  "ND Psycho-Social Rehabilitation",
  "ND Public Administration",
  "ND Social Development",
  "ND Sports Coaching and Training",
  "ND Sports Management",
  "ND Taxation",
  "HND Accountancy",
  "HND Aviation Management",
  "HND Banking and Finance",
  "HND Bilingual Secretarial Studies",
  "HND Business Administration and Management",
  "HND Cooperative Economics & Management",
  "HND Human Resources Management",
  "HND Insurance",
  "HND Local Government Studies",
  "HND Maritime Transport and Business Studies",
  "HND Marketing",
  "HND Microfinance & Enterprise Development",
  "HND Office Technology and Management",
  "HND Official Reporting",
  "HND Parliamentary Administration",
  "HND Pension Administration and Management",
  "HND Petroleum Marketing and Business Studies",
  "HND Procurement and Supply Chain Management",
  "HND Production and Operation Management",
  "HND Psycho-Social Rehabilitation",
  "HND Public Administration",
  "HND Social Development (Community Development & Adult Education)",
  "HND Social Development (Social Development)",
  "HND Social Development (Social Welfare )",
  "HND Social Development (Youth & Sport)",
  "HND Taxation",
  "ND Ceramic Technology",
  "ND Climate Change Science",
  "ND Computer Science",
  "ND Environmental Science and Management Technology",
  "ND Food Science and Technology",
  "ND Forensic Technology",
  "ND Geological Technology",
  "ND Glass Technology",
  "ND Hospitality Management Technology",
  "ND Laundry and Dry-Cleaning Technology",
  "ND Leather Technology",
  "ND Marine Meteorology and Coastal Management",
  "ND Meteorology",
  "ND Nautical Science",
  "ND Polymer Technology",
  "ND Science Laboratory Technology",
  "ND Statistics",
  "ND Textile Technology",
  "ND Tourism Management Technology",
  "ND Water, Sanitation and Hygiene (WASH)",
  "HND Artificial intelligence",
  "HND Ceramic Technology",
  "HND Cybersecurity and Data Protection",
  "HND Environmental Science and Management Technology",
  "HND Food Science and Technology",
  "HND Geological Technology",
  "HND Glass Technology",
  "HND Hospitality Management Technology",
  "HND Leather Technology",
  "HND Nautical Science",
  "HND Networking and Cloud Computing",
  "HND Polymer Technology",
  "HND Science Laboratory Technology (Biochemistry)",
  "HND Science Laboratory Technology (Biochemistry/Chemistry)",
  "HND Science Laboratory Technology (Biochemistry/Microbiology)",
  "HND Science Laboratory Technology (Biology)",
  "HND Science Laboratory Technology (Biology/Microbiology)",
  "HND Science Laboratory Technology (Chemistry)",
  "HND Science Laboratory Technology (Environmental Biology)",
  "HND Science Laboratory Technology (Microbiology)",
  "HND Science Laboratory Technology (Physics with Electronics)",
  "HND Software and Web Development",
  "HND Statistics",
  "HND Textile Technology",
  "HND Tourism Management Technology",
  "Nursing, Health and Related Technology",
  "ND Biomedical Engineering Technology",
  "ND Community Health Technology",
  "ND Dental Surgery Technology",
  "ND Dental Technology",
  "ND Dental Therapy",
  "ND Dispensing Opticianry",
  "ND Environmental Health Technology",
  "ND Epidemiology and Disease Control Technology",
  "ND Family Health Care Technology",
  "ND Health Education and Promotion",
  "ND Health Information Management",
  "ND Medical Imaging Technology",
  "ND Medical Laboratory Technology",
  "ND Medical Store Management Technology",
  "ND Nursing",
  "ND Nutrition and Dietetics",
  "ND Occupational Therapy",
  "ND Orthopaedic Cast Technology",
  "ND Paramedics Technology",
  "ND Pharmacy Technician",
  "ND Physiotherapy",
  "ND Prosthetics & Orthotics Technology",
  "ND Public Health Technology",
  "HND Biomedical Engineering Technology",
  "HND Community Health Technology",
  "HND Dental Surgery Technology",
  "HND Dental Technology",
  "HND Dental Therapy",
  "HND Dispensing Opticianry",
  "HND Environmental Health Technology",
  "HND Health Information Management",
  "HND Medical Imaging Technology",
  "HND Nursing",
  "HND Nutrition and Dietetics",
  "HND Prosthetics & Orthotics Technology",
  "HND Public Health Nursing",
  "HND Orthopaedic Cast Technology",
  "General Studies, Entrepreneurship, Basic",
  "ND Entrepreneurship",
  "ND General Studies",
  "ND Basic Sciences (General)",
  "HND Entrepreneurship",
  "HND General Studies",
  "HND Basic Sciences (General)",
  "HND Mandatory Skills Qualifications (Quality Assurance Assessor)",
  "NTC Agricultural Equipment and Implement",
  "Mechanics Work Practice (New)",
  "NTC & ANTC Animal Husbandry",
  "NTC Crop Production (New)",
  "NTC Fisheries Craft (Aquaculture) (New)",
  "NTC Livestock Production (New)",
  "NTC Mechanized Agriculture (New)",
  "NTC Smart Agriculture (New)",
  "NTC Auto Electrical Wiring (New)",
  "NTC Autobody Works (Panel Beating) (New)",
  "NTC Automobile Mechanics (New)",
  "NTC Autotronic Gas Powered Vehicles (New)",
  "NTC & ANTC Motor Vehicle Mechanics",
  "NTC & ANTC Light Vehicle Body Repairs Work",
  "NTC & ANTC Ceramics",
  "NTC & ANTC Graphic Arts",
  "NTC & ANTC Printing",
  "NTC Carpentry and Joinery (New)",
  "NTC Bricklaying, Block laying & Concreting (New)",
  "NTC & ANTC Furniture Design & Construction",
  "NTC Building Ornamental (New)",
  "NTC Draughtsmanship",
  "NTC Floor/Wall Tiling and Cladding (New)",
  "NTC Furniture Making and Upholstery (New)",
  "NTC & ANTC Machine and Woodworking",
  "NTC & ANTC Painting and Decoration",
  "NTC Painting, Decoration & Finishes (Interior Design) (New)",
  "NTC & ANTC Computer Studies",
  "NTC Artificial Intelligence and Machine Learning Craft (New)",
  "NTC Computer and GSM Handset Maintenance (New)",
  "NTC Creative Content Production (New)",
  "NTC Networking and System Security Work Craft (New)",
  "NTC Robotics Engineering Craft (New)",
  "NTC Social Media Communication and Animation Technology (New)",
  "NTC & ANTC Electrical Installation and Maintenance Work",
  "NTC & ANTC Instrument Mechanics Works",
  "NTC & ANTC Radio, Television and Electronics Work",
  "NTC Electrical Installation and Solar Photovoltaic Installation (New)",
  "NTC Electronic System Maintenance Craft Practice (New)",
  "NTC Industrial Electronics (New)",
  "NTC Catering Craft (New)",
  "Mechanical Trades",
  "NTC & ANTC Foundry",
  "NTC & ANTC Mechanical Engineering Craft Practice",
  "NTC Plumbing and Pipe Fitting (New)",
  "NTC Refrigeration and Air-Conditioning (New)",
  "NTC Blacksmithing and Foundry (New)",
  "NTC Industrial Automation (New)",
  "NTC Industrial Mechanics (New)",
  "NTC Motorcycle and Tricycle Assembly, Repairs and Maintenance (New)",
  "NTC Fabrication and Welding (New)",
  "Textile Trades",
  "NTC & ANTC Ladies Garment Making",
  "NTC & ANTC Men’s Garment Making",
  "NTC Cosmetology (New)",
  "NTC Embellishment Craft (New)",
  "NTC Fashion Design (New)",
  "NTC Fashion/Textile Machine Repairs (New)",
  "NTC Garment Making (New)",
  "NTC & ANTC Leather Works",
  "NTC Leather Craft (Footwears making) (New)",
  "NTC & ANTC Textile",
  "General Studies Subjects",
  "Biology",
  "Chemistry",
  "Economics",
  "English Language",
  "Entrepreneurship",
  "Information and Communication Technology",
  "Mathematics",
  "Physics",
  "Technical Drawing",
  "List of National Vocational Certificate",
  "Curricula and Module Specifications",
  "Agriculture and related sector",
  "NVC Agriculture",
  "Business and related sector",
  "NVC Office Secretarial Assistant",
  "Construction, Engineering and Related sector",
  "NVC Block Laying and Concreting",
  "NVC Carpentry and Joinery",
  "NVC Electrical Installation",
  "NVC Refrigeration and Air-conditioning",
  "Information and Communication Technology and Related Sector",
  "Welding and Fabrication Sector"
];
