import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ShieldCheck, ShieldAlert, FileText, CheckCircle2, AlertTriangle, ArrowLeft } from 'lucide-react';

export default function VerifyTranscript() {
  const { code } = useParams();
  const [status, setStatus] = useState<'loading' | 'valid' | 'invalid' | 'error'>('loading');
  const [data, setData] = useState<any>(null);

  useEffect(() => {
    if (!code) {
      setStatus('invalid');
      return;
    }

    fetch(`/api/public/verify-transcript/${code}`)
      .then(res => {
        if (!res.ok) {
          throw new Error('Invalid');
        }
        return res.json();
      })
      .then(data => {
        setData(data);
        setStatus('valid');
      })
      .catch(() => {
        setStatus('invalid');
      });
  }, [code]);

  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8 flex flex-col items-center">
      <div className="w-full max-w-2xl">
        <Link to="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-slate-700 transition-colors mb-8 font-medium">
          <ArrowLeft className="w-4 h-4" />
          Back to Portal
        </Link>
        
        <div className="bg-white shadow-xl shadow-slate-200/50 rounded-3xl overflow-hidden border border-slate-100">
          <div className="p-8 md:p-12 text-center border-b border-slate-100 bg-slate-900 text-white relative overflow-hidden">
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-slate-800 via-slate-900 to-black"></div>
            <div className="relative z-10 flex flex-col items-center">
              <div className="w-16 h-16 bg-white/10 rounded-2xl flex items-center justify-center mb-6 backdrop-blur-sm border border-white/20">
                <FileText className="w-8 h-8 text-emerald-400" />
              </div>
              <h1 className="text-3xl md:text-4xl font-bold mb-2">Transcript Verification</h1>
              <p className="text-slate-400 text-lg">Official Academic Document Validator</p>
            </div>
          </div>

          <div className="p-8 md:p-12">
            {status === 'loading' && (
              <div className="flex flex-col items-center justify-center py-12 text-slate-500 space-y-4">
                <div className="w-10 h-10 border-4 border-emerald-500/30 border-t-emerald-600 rounded-full animate-spin"></div>
                <p className="font-medium text-lg">Verifying cryptographic signature...</p>
              </div>
            )}

            {status === 'invalid' && (
              <div className="flex flex-col items-center text-center space-y-6 py-8">
                <div className="w-24 h-24 bg-red-100 text-red-600 rounded-full flex items-center justify-center ring-8 ring-red-50 mb-2">
                  <ShieldAlert className="w-12 h-12" />
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-slate-900 mb-2">Verification Failed</h2>
                  <p className="text-slate-600 text-lg">
                    This transcript verification code is invalid, expired, or has been revoked by the institution.
                  </p>
                </div>
                <div className="p-4 bg-red-50 text-red-800 rounded-xl font-mono text-sm w-full">
                  Code: {code}
                </div>
              </div>
            )}

            {status === 'valid' && data && (
              <div className="space-y-8">
                <div className="flex flex-col items-center text-center space-y-4">
                  <div className="w-20 h-20 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center ring-8 ring-emerald-50 mb-2 shadow-inner">
                    <CheckCircle2 className="w-10 h-10" />
                  </div>
                  <div>
                    <h2 className="text-2xl font-bold text-slate-900 flex items-center justify-center gap-2">
                      Authentic Document
                      <ShieldCheck className="w-6 h-6 text-emerald-600" />
                    </h2>
                    <p className="text-emerald-700 font-medium">This transcript was officially generated by the institution.</p>
                  </div>
                </div>

                <div className="bg-slate-50 border border-slate-200 rounded-2xl p-6 md:p-8 space-y-6">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                    <div>
                      <p className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Student Name</p>
                      <p className="text-lg font-semibold text-slate-900">{data.student.name}</p>
                    </div>
                    <div>
                      <p className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Matriculation No.</p>
                      <p className="text-lg font-semibold text-slate-900 font-mono">{data.student.matricNumber}</p>
                    </div>
                    <div className="sm:col-span-2">
                      <p className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Programme</p>
                      <p className="text-lg font-medium text-slate-900">{data.student.programme}</p>
                    </div>
                  </div>

                  <div className="h-px w-full bg-slate-200 my-4"></div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                    <div>
                      <p className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Final CGPA</p>
                      <p className="text-2xl font-bold text-emerald-700">{data.summary.cgpa.toFixed(2)}</p>
                    </div>
                    <div>
                      <p className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Degree Classification</p>
                      <p className="text-lg font-semibold text-slate-900">{data.summary.classification}</p>
                    </div>
                  </div>
                </div>

                <div className="bg-blue-50/50 border border-blue-100 rounded-xl p-5 flex items-start gap-4">
                  <div className="mt-0.5 w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center shrink-0">
                    <ShieldCheck className="w-4 h-4 text-blue-600" />
                  </div>
                  <div>
                    <p className="text-sm font-bold text-blue-900 mb-1">Document Metadata</p>
                    <p className="text-xs text-blue-800 leading-relaxed mb-2">
                      This digital signature verifies that the physical document you are holding exactly matches the secure institutional database record at the time of generation.
                    </p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs font-mono text-blue-900/70">
                      <p><span className="font-bold">TR NO:</span> {data.transcriptNumber}</p>
                      <p><span className="font-bold">DATE:</span> {new Date(data.generatedAt).toLocaleString()}</p>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
        
        <div className="text-center mt-8 text-slate-400 text-sm font-medium">
          <p>© {new Date().getFullYear()} University Registry. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
