import React, { useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { useNotification } from '../contexts/NotificationContext';
import { FileText, FileSignature, Loader2, Save, X } from 'lucide-react';
import jsPDF from 'jspdf';
import { format } from 'date-fns';

export default function ClinicalReportGeneratorWidget({ student, onReportGenerated }: { student: any, onReportGenerated: () => void }) {
  const { token, user } = useAuth();
  const { notify } = useNotification();
  
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportType, setReportType] = useState<'Prescription' | 'Clinical Summary'>('Prescription');
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  
  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsGenerating(true);
    
    try {
      const doc = new jsPDF();
      
      // Header
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      doc.setTextColor(15, 23, 42); // slate-900
      doc.text('Smart Global College Clinic', 14, 20);
      
      doc.setFontSize(14);
      doc.setTextColor(225, 29, 72); // rose-600
      doc.text(reportType === 'Prescription' ? 'Medical Prescription' : 'Clinical Summary Report', 14, 30);
      
      // Patient Info
      doc.setFontSize(11);
      doc.setTextColor(71, 85, 105); // slate-600
      doc.setFont('helvetica', 'normal');
      doc.text(`Date: ${format(new Date(), 'MMMM d, yyyy')}`, 14, 45);
      doc.text(`Patient Name: ${student.name}`, 14, 52);
      doc.text(`Patient ID: ${student.username}`, 14, 59);
      doc.text(`Attending Doctor: Dr. ${user?.name}`, 14, 66);
      
      doc.setDrawColor(226, 232, 240); // slate-200
      doc.line(14, 72, 196, 72);
      
      // Content
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text('Details:', 14, 82);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(51, 65, 85);
      
      const splitContent = doc.splitTextToSize(content, 182);
      doc.text(splitContent, 14, 90);
      
      // Footer
      const finalY = 90 + splitContent.length * 5;
      doc.setFont('helvetica', 'italic');
      doc.text('Doctor\'s Signature: _______________________', 14, finalY + 30);
      
      // Generate base64
      const pdfBase64 = doc.output('datauristring');
      
      // 1. Upload to server
      const uploadRes = await fetch('/api/upload/base64', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          filename: `${reportType.replace(' ', '_')}_${student.username}_${Date.now()}.pdf`,
          base64Data: pdfBase64,
          mimeType: 'application/pdf'
        })
      });
      
      if (!uploadRes.ok) throw new Error('Failed to upload PDF');
      const { fileUrl } = await uploadRes.json();
      
      // 2. Save document record
      const docRes = await fetch(`/api/clinic/student/${student.id}/documents`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          title: title || `${reportType} - ${format(new Date(), 'MMM d, yyyy')}`,
          description: `Generated by Dr. ${user?.name}`,
          category: 'Medical',
          fileUrl,
          fileType: 'application/pdf',
          fileSize: pdfBase64.length
        })
      });
      
      if (docRes.ok) {
        notify({ title: 'Success', message: 'Report generated and saved to patient profile', type: 'success' });
        setTitle('');
        setContent('');
        onReportGenerated();
      } else {
        throw new Error('Failed to save document record');
      }
      
    } catch (err) {
      console.error(err);
      notify({ title: 'Error', message: 'Failed to generate report', type: 'error' });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-sm border border-slate-100 dark:border-slate-700">
      <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-200 mb-6 flex items-center gap-2">
        <FileSignature className="w-5 h-5 text-indigo-500" />
        Generate Clinical Report
      </h3>
      
      <form onSubmit={handleGenerate} className="space-y-4">
        <div className="flex gap-4">
          <label className="flex items-center gap-2 text-sm font-medium text-slate-700 dark:text-slate-300">
            <input 
              type="radio" 
              name="reportType" 
              value="Prescription" 
              checked={reportType === 'Prescription'} 
              onChange={() => setReportType('Prescription')}
              className="text-indigo-600 focus:ring-indigo-500"
            />
            Prescription
          </label>
          <label className="flex items-center gap-2 text-sm font-medium text-slate-700 dark:text-slate-300">
            <input 
              type="radio" 
              name="reportType" 
              value="Clinical Summary" 
              checked={reportType === 'Clinical Summary'} 
              onChange={() => setReportType('Clinical Summary')}
              className="text-indigo-600 focus:ring-indigo-500"
            />
            Clinical Summary
          </label>
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Document Title</label>
          <input
            type="text"
            required
            placeholder={`e.g. ${reportType} for Fever`}
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="w-full px-4 py-2 border border-slate-200 dark:border-slate-700 rounded-lg focus:ring-2 focus:ring-indigo-500 bg-slate-50 dark:bg-slate-900"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Details & Content</label>
          <textarea
            required
            rows={5}
            placeholder={`Type the ${reportType.toLowerCase()} details here...`}
            value={content}
            onChange={(e) => setContent(e.target.value)}
            className="w-full px-4 py-2 border border-slate-200 dark:border-slate-700 rounded-lg focus:ring-2 focus:ring-indigo-500 bg-slate-50 dark:bg-slate-900"
          ></textarea>
        </div>

        <button
          type="submit"
          disabled={isGenerating}
          className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors disabled:opacity-50 font-bold"
        >
          {isGenerating ? <Loader2 className="w-5 h-5 animate-spin" /> : <Save className="w-5 h-5" />}
          Generate & Save to Profile
        </button>
      </form>
    </div>
  );
}
